[phases.setup]
nixPkgs = ["nodejs", "npm"]

[phases.install]
cmds = ["cd apps/api && npm install --legacy-peer-deps"]

[phases.build]
cmds = ["cd apps/api && npm run build"]

[start]
cmd = "cd apps/api && node dist/main.js"
